# Generated by Django 3.2.5 on 2021-07-27 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='このタスクを作った人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(verbose_name='タスク完了時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='終了したかどうか'),
        ),
    ]
