# Generated by Django 3.2.5 on 2021-07-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(null=True, verbose_name='タスク完了時間'),
        ),
    ]
