# Generated by Django 3.2.5 on 2021-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_at',
            field=models.DateField(blank=True, null=True, verbose_name='タスク完了日'),
        ),
    ]
